services:
  _defaults:
    autowire: true
    public: false

  Bex\Behat\BehatRSTSpecificationLocatorExtension\:
    resource: '../../*'

  Doctrine\RST\Parser: ~

  Bex\Behat\BehatRSTSpecificationLocatorExtension\RST\Parser:
    arguments:
      $gherkinParser: '@gherkin.parser'

  Bex\Behat\BehatRSTSpecificationLocatorExtension\Gherkin\Specification\Locator\RSTSpecificationLocator:
    arguments:
      $gherkin: '@gherkin'
      $basePath: '%paths.base%'
    tags:
      - { name: 'specifications.locator', priority: 60 }

  Bex\Behat\BehatRSTSpecificationLocatorExtension\RST\Loader\RSTFileLoader:
    arguments:
      $basePath: '%paths.base%'
    tags:
      - { name: 'gherkin.loader', priority: 60 }